name: HDB
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - ipywidgets
  - scikit-learn
  - matplotlib
  - tqdm
  - pip
  - pip:
      - torch>=1.8.1
      - torchvision>=0.9.1
