name: HDB
channels:
  - pytorch
  - conda-forge
  - pyg
  - defaults
dependencies:
  - python=3.9
  - jupyterlab
  - ipywidgets
  - scikit-learn
  - sympy
  - matplotlib
  - seaborn
  - tqdm
  - cpuonly=1.0=0
  - pytorch=1.9.0
  - torchaudio=0.9.0
  - torchdiffeq
  - torchvision=0.2.2
  - tensorboard
  - pytorch-scatter
  - xgboost
  - shap
  - optuna
