name: HDB
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python
  - jupyterlab
  - ipywidgets
  - scikit-learn
  - sympy
  - matplotlib
  - seaborn
  - tqdm
  - pytorch>=1.8.1
  - torchvision>=0.9.1
  - torchdiffeq
